### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ofcansh** [FirezTheGreat/Hope#1]
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/AprovedBot/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/AprovedBot/node_modules/discord.js/src/index.js
- /home/runner/AprovedBot/structures/Hope.js
- /home/runner/AprovedBot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/AprovedBot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/AprovedBot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/AprovedBot/node_modules/discord.js/src/index.js',
    '/home/runner/AprovedBot/structures/Hope.js',
    '/home/runner/AprovedBot/index.js'
  ]
}

I did npm i and other stuff but cant work ...

**Comment by ofcansh** [comment]
nvm i fixed it

**Comment by ofcansh** [comment]
Error: Cannot find module '../structures/music/erela'
Require stack:
- /home/runner/komedy/structures/Hope.js
- /home/runner/komedy/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Hope (/home/runner/komedy/structures/Hope.js:26:22)
    at Object.<anonymous> (/home/runner/komedy/index.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/komedy/structures/Hope.js',
    '/home/runner/komedy/index.js'
  ]
}


But, this is the new error

**Comment by FirezTheGreat** [comment]
need to create a directory of structures/music/erela

**Comment by FirezTheGreat** [comment]
wait, where did you get this error??

From which file?

**Comment by FirezTheGreat** [comment]
music has been totally removed in HOPE v2, so i cant really tell where that error is coming from unless i know what command is triggering it.

**Comment by FirezTheGreat** [comment]
#2
